package com.example.demo.kafka;

import com.example.demo.entity.Trade;
import com.example.demo.service.TradeConsumer;
import com.example.demo.service.TradeService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.kafka.test.context.EmbeddedKafka;
import org.springframework.test.annotation.DirtiesContext;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.concurrent.TimeUnit;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;
import static org.awaitility.Awaitility.await;

@SpringBootTest
@DirtiesContext
@EmbeddedKafka(partitions = 2)
@org.springframework.test.context.TestPropertySource(properties = {
    "spring.flyway.enabled=false",
    "spring.jpa.hibernate.ddl-auto=create-drop",
    "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect"
})
public class KafkaRetryIntegrationTest {

    @Autowired
    private KafkaTemplate<String, Object> kafkaTemplate;

    // We mock the TradeService so we can force it to throw exceptions
    // and spy on how many times it was called by the retry mechanism.
    @MockitoBean
    private TradeService tradeService;

    @Autowired
    private TradeConsumer tradeConsumer;

    @org.springframework.test.context.DynamicPropertySource
    static void kafkaProperties(org.springframework.test.context.DynamicPropertyRegistry registry) {
        // This overrides the bootstrap-servers from application.properties
        // and injects the dynamic port generated by @EmbeddedKafka
        registry.add("spring.kafka.bootstrap-servers", 
                     () -> System.getProperty("spring.embedded.kafka.brokers"));
    }

    @Test
    public void testRetryAndDltRouting() {
        // Arrange: Make the trade service ALWAYS fail
        doThrow(new RuntimeException("Simulated Database Failure!"))
                .when(tradeService).saveTrade(any(Trade.class));

        Trade trade = new Trade();
        trade.setSymbol("TEST-USD");
        trade.setExchange("TEST");
        trade.setPrice(new BigDecimal("1000.0"));
        trade.setQuantity(new BigDecimal("1.0"));
        trade.setTradeTimestamp(Instant.now());

        // Act: Send a single message to the raw topic
        kafkaTemplate.send("trades.raw", trade.getSymbol(), trade);

        // Assert:
        // We configured maxAttempts = 3 (1 initial attempt + 2 retries).
        // Since it's fixed backoff of 2 seconds, it should take at least 4 seconds for all 3 attempts.
        // We wait up to 10 seconds for the service to be invoked exactly 3 times.
        await().atMost(10, TimeUnit.SECONDS).untilAsserted(() -> {
            verify(tradeService, times(3)).saveTrade(any(Trade.class));
        });

        // The message is then routed to 'retry-2000-dlt', which DeadLetterConsumer picks up.
        // You will see the DLT consumer logging the failure in the console!
    }
}
